/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard-scss'],
  ignoreFiles: [
    'node_modules/**',
    'app/**',
    'src/styles/_normalize.scss',
    'src/styles/helpers/_mixins.scss',
  ],
  rules: {
    'color-no-invalid-hex': true,
    'font-family-no-duplicate-names': true,
    'font-family-no-missing-generic-family-keyword': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'unit-no-unknown': true,
    'keyframe-declaration-no-important': true,
    'declaration-block-no-duplicate-properties': true,
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': true,
    'comment-no-empty': true,
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'no-empty-source': true,
    'block-no-empty': [true, { severity: 'warning' }],
    'no-invalid-double-slash-comments': true,
    'color-function-notation': 'legacy',
    'length-zero-no-unit': true,
    'font-weight-notation': 'numeric',
    'shorthand-property-no-redundant-values': true,
    'declaration-no-important': [true, { severity: 'warning' }],
    'selector-pseudo-element-colon-notation': 'double',
    'selector-class-pattern':
      '^[a-z][a-zA-Z0-9]*(-[a-z0-9]+)*(__[a-z0-9]+(-[a-z0-9]+)*)?(--[a-z0-9]+(-[a-z0-9]+)*)?$',
    'custom-property-empty-line-before': null,
    'alpha-value-notation': 'number',
    'color-hex-length': 'long',
    'function-name-case': 'lower',
    'function-url-quotes': 'always',
    'value-keyword-case': [
      'lower',
      {
        camelCaseSvgKeywords: false,
        severity: 'warning',
      },
    ],
    'scss/at-rule-no-unknown': true,
    'font-family-name-quotes': null,
  },
}
